dependencies:
  - "OpenZeppelin/openzeppelin-contracts@4.4.0"
  - "smartcontractkit/chainlink@2.2.0"

compiler:
  solc:
    remappings:
      - "@openzeppelin-contracts=OpenZeppelin/openzeppelin-contracts@4.4.0"
      - "@openzeppelin/contracts=OpenZeppelin/openzeppelin-contracts@4.4.0"
      - "@chainlink=smartcontractkit/chainlink@2.2.0"
