dependencies:
  - "OpenZeppelin/openzeppelin-contracts@4.4.0"
  - "bugout-dev/dao@0.0.7"
  - "smartcontractkit/chainlink@1.13.3"

compiler:
  solc:
    remappings:
      - "@openzeppelin-contracts=OpenZeppelin/openzeppelin-contracts@4.4.0"
      - "@openzeppelin/contracts=OpenZeppelin/openzeppelin-contracts@4.4.0"
      - "@moonstream=bugout-dev/dao@0.0.7"
      - "@chainlink=smartcontractkit/chainlink@1.13.3"
