name: Lint Engine API

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "api/**"
      - "!api/deploy/**"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Upgrade pip and setuptools
        run: pip install --upgrade pip setuptools
      - name: Install requirements
        run: pip install --exists-action i -r requirements.txt
        working-directory: ./api
      - name: Install dev dependencies
        run: pip install black
      - name: Black syntax check
        working-directory: ./api
        run: black --check engineapi/
