name: Diamond Reentrancy Guard tests

on:
    pull_request:
        paths:
            - "contracts/test/**"
            - "contracts/diamond/security/DiamondReentrancyGuard.sol"
            - "cli/web3cli/test_reentrancy_guard.py"
            - "cli/web3cli/ExploitContract.py"
            - "cli/web3cli/ReentrancyExploitable.py"
            - "cli/web3cli/Diamond*"
            - "cli/web3cli/OwnershipFacet.py"
            - ".github/workflows/reentrancy-guard.yml"
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: "16"
            - uses: actions/setup-python@v2
              with:
                  python-version: "3.9"
            - name: Install ganache
              run: npm install -g ganache-cli
            - name: Upgrade pip
              env:
                  BROWNIE_LIB: 1
              run: pip install -U pip
            - name: Install additional dev dependencies
              run: |
                  pip install black moonworm
            - name: Install dependencies for CLI
              working-directory: cli/
              env:
                  BROWNIE_LIB: 1
              run: |
                  pip install -e .
            - name: Run tests
              working-directory: cli/
              run: bash test.sh web3cli.test_crafting
